name: Feature Request
description: Suggest a feature for this library
labels: ["enhancement"]
body:
  - type: input
    attributes:
      label: Summary
      description: >
        A short summary of what your feature request is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the feature request for?
      description: Why is it relevant?
    validations:
      required: true
  - type: textarea
    attributes:
      label: How should we approach this feature?
      description: Describe how should it be implemented?
  - type: textarea
    attributes:
      label: Additional Context
      description: If there is anything else to say, please do so here.
